#!/bin/sh

##BEGIN TEMPLATE WRAPPER SHELL SCRIPT

# A variable to hold arguments after we strip OpenStep specific information
args=

# If you are debugging this script you might uncomment the following
# two lines.
#set -x
#echo input=$*

# Loop until argv ($#) is zero, each iteration will decrement (shift)
# argv/argc.
while [ $# != 0 ] ; do
  case $1 in
    # -NSOpen is an OpenStep standard command line flag which
    # lets the NSApplication know what file to open.
    -NSOpen)
        args="$args $2"
        shift             
        ;;
    # -NSOpenTemp is an OpenStep standard command line flag which
    # lets the NSApplication know what file to open and that it is
	# a temporary file and should be resaved somewhere else if edited.
    -NSOpenTemp)
        args="$args $2"
        shift
        ;;
    # -_NSMachLaunch is an undocumented additional flag to NSApplication.
    # We just ignore it here.
    -_NSMachLaunch)
        shift
        ;;
    *)
        args="$args $1"
        ;;
  esac
  shift
done

##END OF TEMPLATE WRAPPER SHELL SCRIPT

## Call apps through appfind wrapper (wrap the wrapper ;0)
#
# Insert any varargs() here
MSG="This is just a template wrapper for tutorial purposes. \
Please use your favorite editor (vi) for viewing the syntax \
of the script."; export MSG
#
# This is where the initial work is done, and the result is 
# sent to /usr/openstep/bin/appfind
APP=appname; export APP
WRAP=/usr/openstep/bin/appfind
args="-args -to -application"
exec $WRAP $args 
