/*
 * Copyright_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `Copyright.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "Copyright_ui.h"

char sccsid[] = "@(#)LuBu OpenMagic 1.0, 06/03/10"; 

/*
 * Initialize an instance of object `popup1'.
 */
Copyright_popup1_objects *
Copyright_popup1_objects_initialize(Copyright_popup1_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (Copyright_popup1_objects *) calloc(1, sizeof (Copyright_popup1_objects))))
		return (Copyright_popup1_objects *) NULL;
	if (!ip->popup1)
		ip->popup1 = Copyright_popup1_popup1_create(ip, owner);
	if (!ip->textpane1)
		ip->textpane1 = Copyright_popup1_textpane1_create(ip, ip->popup1);
	return ip;
}

/*
 * Create object `popup1' in the specified instance.
 */
Xv_opaque
Copyright_popup1_popup1_create(Copyright_popup1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 597,
		XV_HEIGHT, 390,
		XV_LABEL, "Lubu OpenMagic 1.0 Copyright Notice",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `textpane1' in the specified instance.
 */
Xv_opaque
Copyright_popup1_textpane1_create(Copyright_popup1_objects *ip, Xv_opaque owner)
{
	extern Notify_value	Copyright_popup1_textpane1_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	
	obj = xv_create(owner, TEXTSW,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		OPENWIN_SHOW_BORDERS, FALSE,
		TEXTSW_BROWSING, TRUE,
		TEXTSW_DISABLE_LOAD, TRUE,
		NULL);
	xv_set(textsw_first(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_MOVE,
		LOC_DRAG,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		WIN_LEFT_KEYS,
		WIN_RIGHT_KEYS,
		WIN_TOP_KEYS,
		NULL, NULL);
	notify_interpose_event_func(textsw_first(obj),
		(Notify_func) Copyright_popup1_textpane1_event_callback, NOTIFY_SAFE);
	return obj;
}

