/*
 * Copyright_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `Copyright.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "Copyright_ui.h"


/*
 * Global object definitions.
 */
Copyright_popup1_objects	*Copyright_popup1;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(int argc, char **argv)
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Copyright_popup1 = Copyright_popup1_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Copyright_popup1->popup1);
	exit(0);
}

#endif


/*
 * Event callback function for `textpane1'.
 */
Notify_value
Copyright_popup1_textpane1_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	Copyright_popup1_objects *ip = (Copyright_popup1_objects *) xv_get(xv_get(win, XV_OWNER), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "Copyright: Copyright_popup1_textpane1_event_callback: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Copyright_popup1->textpane1, TEXTSW_FILE, "Copyright.txt", NULL);
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}
