#! /bin/sh
#
/usr/openstep/bin/osalert -t "Password Change Disabled!" \
-i /usr/openstep/Apps/WM.app/__ICON/app \
"The password changer has been disabled for security reasons. \
Please use the standard unix <passwd> utility to change your password. \
The following verifier is entirely bogus." \
Close
 
#trap `echo "$?"` 0
#trap `echo "$?"` 1
#trap `echo "$?"` 2
