.\" "@(#) open.1, Rev 1.3, 97/03/17"
.\"
.\"	Copyright (c) 1995-1996, Sun Microsystems, Inc.
.\"     portions (c) Copyright 1994, NeXT Computer, Inc.
.\"     All rights reserved.
.\"
.TH open 1 "22 Jul 1996" "Sun Microsystems, Inc." "OpenStep Commands"
.SH NAME
open \- open files
.SH SYNOPSIS
\fBopen\fR [ -a \fIapp\fR ] [ -o ] [ -p ] [ -NSHost \fIhostname\fR ] \fIfilename\fR ...
.SH DESCRIPTION
The \fBopen\fR command opens a file (or a directory), just as if you had
double-clicked the file's icon.
.PP
You can specify one or more
file names (or pathnames), which are interpreted relative to the Shell
or Terminal window's current working directory.  For example, the following
command would open all WriteNow files in the current working directory:
.nf

	open *.wn

.fi
.SH ARGUMENTS
.TP 9
.B \-a
specifies an application to use for opening the file.
.TP 9
.B \-o
opens the file (can be used in combination with
.BR \-p ).
.TP 9
.B \-p
causes the file to be printed instead of opened.
.TP 9
.B \-NSHost
opens the file on the specified host (if its window server is public).

