/*
 * Test_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `Test.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "Test_ui.h"

/*
 * Create object `menu1' in the specified instance.
 */
Xv_opaque
Test_menu1_create(caddr_t ip, Xv_opaque owner)
{
	extern Menu		quit(Menu, Menu_generate);
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_GEN_PROC, exit,
		MENU_TITLE_ITEM, owner ? "" : "File",
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Quit ..",
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "File",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `popup1'.
 */
Test_popup1_objects *
Test_popup1_objects_initialize(Test_popup1_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (Test_popup1_objects *) calloc(1, sizeof (Test_popup1_objects))))
		return (Test_popup1_objects *) NULL;
	if (!ip->popup1)
		ip->popup1 = Test_popup1_popup1_create(ip, owner);
	if (!ip->canvas1)
		ip->canvas1 = Test_popup1_canvas1_create(ip, ip->popup1);
	return ip;
}

/*
 * Create object `popup1' in the specified instance.
 */
Xv_opaque
Test_popup1_popup1_create(Test_popup1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 400,
		XV_HEIGHT, 150,
		XV_LABEL, "Popup Window",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `canvas1' in the specified instance.
 */
Xv_opaque
Test_popup1_canvas1_create(Test_popup1_objects *ip, Xv_opaque owner)
{
	extern Notify_value	Test_popup1_canvas1_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_MOVE,
		LOC_DRAG,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		WIN_LEFT_KEYS,
		WIN_RIGHT_KEYS,
		WIN_TOP_KEYS,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) Test_popup1_canvas1_event_callback, NOTIFY_SAFE);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

