/*
 * Test_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `Test.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "Test_ui.h"


/*
 * Global object definitions.
 */
Test_popup1_objects	*Test_popup1;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(int argc, char **argv)
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Test_popup1 = Test_popup1_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Test_popup1->popup1);
	exit(0);
}

#endif


/*
 * Menu handler for `menu1'.
 */
Menu
quit(Menu menu, Menu_generate op)
{
	Xv_opaque ip = (Xv_opaque) xv_get(menu, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		fputs("Test: exit: MENU_NOTIFY\n", stderr);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return menu;
}

/*
 * Event callback function for `canvas1'.
 */
Notify_value
Test_popup1_canvas1_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	Test_popup1_objects *ip = (Test_popup1_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "Test: Test_popup1_canvas1_event_callback: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Test_popup1->canvas1, XV_SHOW, TRUE, NULL);
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

